### ISSUE TITLE
无法使用啊（已解决）

### ISSUE THREAD

**Issue by wqjuser** [mcxtzhang/all-base-adapter#1]
Error:(29, 13) Failed to resolve: com.github.mcxtzhang:all-base-adapter:V1.0.0

**Comment by mcxtzhang** [comment]
引入jitpack了吗？

**Comment by wqjuser** [comment]
引入了

**Comment by mcxtzhang** [comment]
我这边试了 完全正常。你check一下吧

**Comment by wqjuser** [comment]
对于listview是不是就要用commonadapter而不能用addview了

**Comment by wqjuser** [comment]
目前ViewGroupUtils可以使用但是对于listview无法找到CommonAdapter

**Comment by mcxtzhang** [comment]
建议大兄弟仔细看看Demo 谢谢。

**Comment by mcxtzhang** [comment]
另外 最近release还在upload中。如果想用ListView、RecyclerView要稍等。

**Comment by wqjuser** [comment]
哦

**Comment by mcxtzhang** [comment]
compile 'com.github.mcxtzhang:all-base-adapter:V1.1.0'

**Comment by wqjuser** [comment]
感谢
